### ISSUE TITLE
Eliminate GitHub warnings, update Note.js to 20

### ISSUE THREAD

**Issue by hwf1324** [carlosperate/download-file-action#36]
Currently GitHub comes up with the following warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: carlosperate/download-file-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by carlosperate** [comment]
This should be fixed in the v2.0.2 release, thanks for the report!
